#!/bin/bash




# -------- DEFINITIONS --------

#exit on error
set -e

#current executable directory
CXD=$(dirname $(readlink -f $0))
pCXD=$(dirname $CXD)

#paths
OUT=$pCXD/out
TMP=$OUT/tmp






# -------- PREPARE ENVIRONMENT --------

#clean
$CXD/clean

#remove previous generations
rm --recursive --force $OUT/src/
if [[ ! -d $TMP ]]; then mkdir --parents $TMP; fi






# -------- EXECUTION --------

#get into tmp dir
cd $TMP

#arch type given as 1st param
if [[ -z $1 ]]; then
	echo "build: Missing <archType> as 1st argument." >&2
	exit 1
fi

#args
archType=$1
if [[ $archType != '32' && $archType != '64' ]]; then
	echo "build: Invalid <archType> given '$archType'." >&2
	exit 1
fi

#gen N file with all the requirements
$CXD/genOperators $archType
