#!/usr/bin/python3



# -------- IMPORTATIONS --------

#system
import os, sys






# -------- DECLARATIONS --------

#current executable directory
CXD = os.path.realpath(os.path.dirname(sys.argv[0]))
pCXD     = os.path.dirname(CXD)

#paths
SRC_DIR     = pCXD + "/src"
DST_DIR     = pCXD + "/out/src"
DST_FILE    = DST_DIR + "/operators.n"

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< tmp
DST_FILE_FP__TMP_LLI = DST_DIR + "/operators.n.cfg.TMP_FOR_LLI_CPL"
DST_FILE_FP__TMP_Z   = DST_DIR + "/operators.n.cfg.TMP_FOR_Z_CPL"






# -------- TOOLS --------

#errors
def err(msg, code=1):
	print("genOperators: " + msg)
	exit(code)






# -------- TOOLS --------

#get each file in a dir recursively
def fse__getTree(dir, ignoreHidden=True):
	res = []
	for fseName in os.listdir(dir):

		#hidden file
		if ignoreHidden:
			if fseName[0] == '.':
				continue

		#full path
		fseFullPath = dir + '/' + fseName

		#dir => add its content recursively
		if os.path.isdir(fseFullPath):
			res += fse__getTree(fseFullPath)

		#else, simply add it
		else:
			res.append(fseFullPath)
	return res

def catFullTreeIntoDst(srcDir):
	for filePath in fse__getTree(srcDir):
		os.system("cat "       + filePath + " >> " + DST_FILE)

		#also store first line in fp <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< tmp
		os.system("head -n 1 " + filePath + "| sed 's@{@;@' >> " + DST_FILE_FP__TMP_LLI)






# -------- INITIALIZATION --------

#get arch type
arch_subdir = "arch32"
if len(sys.argv) < 2:
	err("Missing arch type 32 or 64 as 1st argument.")
if sys.argv[1] == "64":
	arch_subdir = "arch64"
elif sys.argv[1] != "32":
	err("Invalid value \"" + sys.argv[1] + "\" given as arch type (expected \"32\" or \"64\").", 2)






# -------- EXECUTION --------

#create dst dir
if not os.path.isdir(os.path.abspath(DST_DIR)):
	os.makedirs(DST_DIR)

#copy generic content
catFullTreeIntoDst(SRC_DIR + "/gnc")

#add specific content (32/64)
catFullTreeIntoDst(SRC_DIR + '/' + arch_subdir)

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< tmp
f = open(DST_FILE_FP__TMP_LLI)
lines = f.read().split('\n')
f.close()

def unpfxTypeName(n): #small version just for our need
	if n == "void":
		return n
	if n.startswith("GU"):
		return n[2:]
	elif n.startswith("GD"):
		tmp = n.split("_GU")
		return tmp[0][2:] + '[' + tmp[1] + ']'
	raise ValueError("Type \"" + n + "\" not taken in charge in bld for now.")

#make z fp from LLI fp
z_fp = ""
for l in lines:
	l = l.strip()
	if len(l) == 0:
		continue
	tmp    = l.split(' ')
	retTyp = unpfxTypeName(tmp[0])
	tmp    = ' '.join(tmp[1:]).split('(')
	name   = tmp[0]
	params = tmp[1].split(')')[0].split(', ')
	for p in range(len(params)):
		params[p] = unpfxTypeName(params[p].split(' ')[0])
	z_fp += 'f' + name + "\t\t" + retTyp + ',' + ','.join(params) + '\n'

f = open(DST_FILE_FP__TMP_Z, 'w')
f.write(z_fp)
f.close()
